version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
before_build:
- cmd: nuget restore
build:
  verbosity: minimal
artifacts:
- path: '**/Chef.PowerShell.dll'
- path: '**/Chef.PowerShell.pdb'
- path: '**/Chef.PowerShell.reg'