[chef-powershell-shim]
build_targets = [
  "x86_64-windows"
]
plan_path = "habitat"

[chef-powershell-shim-x86]
build_targets = [
  "x86_64-windows"
]
plan_path = "habitat-x86"

[dotnet-45-dev-pack-x86]
build_targets = [
  "x86_64-windows"
]
plan_path = "habitat-dotnet-45-dev-pack-x86"

[dotnet-core-sdk-x86]
build_targets = [
  "x86_64-windows"
]
plan_path = "habitat-dotnet-core-sdk-x86"

[visual-build-tools-2019-x86]
build_targets = [
  "x86_64-windows"
]
plan_path = "habitat-vs-2019-x86"

[windows-10-sdk-x86]
build_targets = [
  "x86_64-windows"
]
plan_path = "habitat-win-10-sdk-x86"
