# frozen_string_literal: true
source "https://rubygems.org"

gem "rubocop", ">= 1.22.0"
gem "rspec"
gem "chefstyle"
gem "libyajl2"

gemspec

group(:development, :test) do
  gem "fauxhai-ng"
  gem "rake"
end
