# frozen_string_literal: true
source "https://rubygems.org"

gem "rspec"
gem "pry"

gem "ffi", ">= 1.15", force_ruby_platform: true

gemspec

group(:development, :test) do
  gem "fauxhai-ng"
  gem "rake"
end
