name: Chef-PowerShell Builder
# on: [push]
# working dir : D:\a\chef-powershell-shim\chef-powershell-shim
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  Build-And-Push-Chef-PowerShell-Gem:
    if: github.event.pull_request.merged == true
    runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - run: .\.expeditor\manual-gem-release.ps1
      - name: basic powershell commands
        env:
          MY_NAME: John McCrae
        run: |
          Get-Date
          Write-Output $env:MY_NAME
        shell: powershell
