name: Manually triggered workflow
on:
  workflow_dispatch:

jobs:
  Build-And-Push-Chef-PowerShell-Gem:
    if: github.event_name == 'workflow_dispatch'
    runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: basic powershell commands
        env:
          MY_NAME: John McCrae
        run: |
          Get-Date
          Write-Output $env:MY_NAME
        shell: powershell
      - name: Manually Build Gem
        uses: Amadevus/pwsh-script@v2
        id: script
        with:
          script: |

            $ErrorActionPreference = "Stop"

            $project_name = "chef-powershell"

            Write-Output "--- Making sure we're in the correct spot"
            # $project_root = (Get-ChildItem c:\ -Recurse | Where-Object { $_.PSIsContainer -and $_.Name.EndsWith($("$project_name-shim")) } | Select-Object -First 1).FullName
            # Set-Location -Path $project_root
            # Get-Location
            $pwd
            Write-Output "`r"

            Write-Output "-- Is Habitat actually installed?"
            # Is hab installed?
            if (-not (Get-Command -Name Hab -ErrorAction SilentlyContinue)) {
                Write-Output "--- No, Installing Habitat via Choco"
                choco install habitat -y
                if (-not $?) { throw "unable to install Habitat" }
                Write-Output "`r"
            }
            Write-Output "`r"
