name: Manually triggered workflow
on:
  workflow_dispatch:

jobs:
  Build-And-Push-Chef-PowerShell-Gem:
    if: github.event_name == 'workflow_dispatch'
    runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - run: . .\.expeditor\manual-gem-release.ps1
      - name: basic powershell commands
        env:
          MY_NAME: John McCrae
        run: |
          Get-Date
          Write-Output $env:MY_NAME
        shell: powershell
