# working dir : D:\a\chef-powershell-shim\chef-powershell-shim
name: Test Mule
on:
  workflow_dispatch:

jobs:
  Test-Crap:
    if: github.event_name == 'workflow_dispatch'
    runs-on: windows-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
      - name: Run the PowerShell Script to Update the Gem version, maybe
        run: |
          $project_root = $pwd
          Write-Output $project_root
          $foo = Get-Childitem -path .
          Write-Output $foo
        shell: powershell
